Refactor
Fly-Style/hazelcast pull request #958
Opened 2022-11-08 15:40 UTC by burakgok

2022-11-08 19:07 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRel.java
> -    // Copy of org.apache.calcite.rel.core.Sort.computeSelfCost, but also takes our requiresSort flag into account
Why was it removed?

2022-11-08 19:19 UTC, Fly-Style requested changes

2022-11-08 19:19 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        for (RelNode physicalInput : OptUtils.extractPhysicalRelsFromSubset(sort.getInput())) {
Why rename this? It's a highlight that input was converted with `PHYSICAL`trait.

2022-11-08 19:19 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> +        // FullScan + Sort + Limit
Limit is not always present in the plan. Even -- likely would not be present.

2022-11-08 19:19 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        default RelOptRule toRule() {
We prefer to use Dependency Inversion :)

2022-11-08 19:57 UTC, burakgok commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        default RelOptRule toRule() {
I followed the second guideline for writing rules, explained in the [RelRule Javadoc](https://calcite.apache.org/javadocAggregate/org/apache/calcite/plan/RelRule.html). It is also used to initialize `INSTANCE`.

2022-11-08 19:57 UTC, burakgok commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> +        // FullScan + Sort + Limit
It does not matter whether LIMIT exists in the plan. The comments show what is stored in the lists. It can be written as `LIMIT?` or `[LIMIT]` to indicate it is optional, but I think it would not be easier to understand.

2022-11-08 19:57 UTC, burakgok commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        for (RelNode physicalInput : OptUtils.extractPhysicalRelsFromSubset(sort.getInput())) {
I am reassigning that variable, so that it no longer stores the physical input.

2022-11-09 10:38 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        for (RelNode physicalInput : OptUtils.extractPhysicalRelsFromSubset(sort.getInput())) {
If so, I'd recommend you to store it in separate variable.

2022-11-09 10:43 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> -        default RelOptRule toRule() {
It's great, but the project uses the Dependency Inversion principle here, check any rule in `PhysicalRules`. If you want to change that behavior, it's a good candidate for a separate PR..

2022-11-09 10:44 UTC, Fly-Style commented on hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/SortPhysicalRule.java
> +        // FullScan + Sort + Limit
Can't agree with you, such indication (` + [LIMIT]`) is a common practice inherited from Computer Science

2022-11-09 13:11 UTC, Fly-Style approved these changes
LGTM, great job!

2022-11-09 13:11 UTC, merged